# Generated by Django 4.2.7 on 2023-11-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_signup_club_alter_signup_email_alter_signup_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=150)),
                ('std_id', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('join_date', models.DateField(null=True)),
            ],
        ),
    ]
