# Generated by Django 4.2.7 on 2023-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.ImageField(null=True, upload_to='media/signup'),
        ),
    ]
