# Generated by Django 4.2.7 on 2023-11-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_signup_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='image',
            new_name='member_image',
        ),
    ]
