# Generated by Django 4.2.7 on 2023-11-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_image_member_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.FileField(null=True, upload_to='media/signup/'),
        ),
    ]
