# Generated by Django 4.2.7 on 2023-11-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_signup_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='mem_name',
        ),
    ]
